# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\E5Gui\E5ToolBarDialog.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_E5ToolBarDialog(object):
    def setupUi(self, E5ToolBarDialog):
        E5ToolBarDialog.setObjectName("E5ToolBarDialog")
        E5ToolBarDialog.resize(600, 500)
        E5ToolBarDialog.setSizeGripEnabled(True)
        self.vboxlayout = QtWidgets.QVBoxLayout(E5ToolBarDialog)
        self.vboxlayout.setObjectName("vboxlayout")
        self.hboxlayout = QtWidgets.QHBoxLayout()
        self.hboxlayout.setObjectName("hboxlayout")
        self.label = QtWidgets.QLabel(E5ToolBarDialog)
        self.label.setObjectName("label")
        self.hboxlayout.addWidget(self.label)
        self.toolbarComboBox = QtWidgets.QComboBox(E5ToolBarDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolbarComboBox.sizePolicy().hasHeightForWidth())
        self.toolbarComboBox.setSizePolicy(sizePolicy)
        self.toolbarComboBox.setObjectName("toolbarComboBox")
        self.hboxlayout.addWidget(self.toolbarComboBox)
        self.newButton = QtWidgets.QPushButton(E5ToolBarDialog)
        self.newButton.setObjectName("newButton")
        self.hboxlayout.addWidget(self.newButton)
        self.removeButton = QtWidgets.QPushButton(E5ToolBarDialog)
        self.removeButton.setObjectName("removeButton")
        self.hboxlayout.addWidget(self.removeButton)
        self.renameButton = QtWidgets.QPushButton(E5ToolBarDialog)
        self.renameButton.setObjectName("renameButton")
        self.hboxlayout.addWidget(self.renameButton)
        self.vboxlayout.addLayout(self.hboxlayout)
        self.line = QtWidgets.QFrame(E5ToolBarDialog)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.vboxlayout.addWidget(self.line)
        self.gridlayout = QtWidgets.QGridLayout()
        self.gridlayout.setObjectName("gridlayout")
        self.label_2 = QtWidgets.QLabel(E5ToolBarDialog)
        self.label_2.setObjectName("label_2")
        self.gridlayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(E5ToolBarDialog)
        self.label_3.setObjectName("label_3")
        self.gridlayout.addWidget(self.label_3, 0, 2, 1, 1)
        self.actionsTree = QtWidgets.QTreeWidget(E5ToolBarDialog)
        self.actionsTree.setAlternatingRowColors(True)
        self.actionsTree.setRootIsDecorated(False)
        self.actionsTree.setObjectName("actionsTree")
        self.gridlayout.addWidget(self.actionsTree, 1, 0, 3, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridlayout.addItem(spacerItem, 1, 1, 1, 1)
        self.toolbarActionsList = QtWidgets.QListWidget(E5ToolBarDialog)
        self.toolbarActionsList.setObjectName("toolbarActionsList")
        self.gridlayout.addWidget(self.toolbarActionsList, 1, 2, 3, 1)
        self.gridlayout1 = QtWidgets.QGridLayout()
        self.gridlayout1.setSpacing(0)
        self.gridlayout1.setObjectName("gridlayout1")
        self.upButton = QtWidgets.QToolButton(E5ToolBarDialog)
        self.upButton.setText("")
        self.upButton.setObjectName("upButton")
        self.gridlayout1.addWidget(self.upButton, 0, 1, 1, 1)
        self.leftButton = QtWidgets.QToolButton(E5ToolBarDialog)
        self.leftButton.setText("")
        self.leftButton.setObjectName("leftButton")
        self.gridlayout1.addWidget(self.leftButton, 1, 0, 1, 1)
        self.rightButton = QtWidgets.QToolButton(E5ToolBarDialog)
        self.rightButton.setText("")
        self.rightButton.setObjectName("rightButton")
        self.gridlayout1.addWidget(self.rightButton, 1, 2, 1, 1)
        self.downButton = QtWidgets.QToolButton(E5ToolBarDialog)
        self.downButton.setText("")
        self.downButton.setObjectName("downButton")
        self.gridlayout1.addWidget(self.downButton, 2, 1, 1, 1)
        self.gridlayout.addLayout(self.gridlayout1, 2, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridlayout.addItem(spacerItem1, 3, 1, 1, 1)
        self.vboxlayout.addLayout(self.gridlayout)
        self.buttonBox = QtWidgets.QDialogButtonBox(E5ToolBarDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Apply|QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok|QtWidgets.QDialogButtonBox.Reset|QtWidgets.QDialogButtonBox.RestoreDefaults)
        self.buttonBox.setObjectName("buttonBox")
        self.vboxlayout.addWidget(self.buttonBox)
        self.label.setBuddy(self.toolbarComboBox)

        self.retranslateUi(E5ToolBarDialog)
        QtCore.QMetaObject.connectSlotsByName(E5ToolBarDialog)
        E5ToolBarDialog.setTabOrder(self.toolbarComboBox, self.newButton)
        E5ToolBarDialog.setTabOrder(self.newButton, self.removeButton)
        E5ToolBarDialog.setTabOrder(self.removeButton, self.renameButton)
        E5ToolBarDialog.setTabOrder(self.renameButton, self.actionsTree)
        E5ToolBarDialog.setTabOrder(self.actionsTree, self.toolbarActionsList)
        E5ToolBarDialog.setTabOrder(self.toolbarActionsList, self.upButton)
        E5ToolBarDialog.setTabOrder(self.upButton, self.downButton)
        E5ToolBarDialog.setTabOrder(self.downButton, self.rightButton)
        E5ToolBarDialog.setTabOrder(self.rightButton, self.leftButton)
        E5ToolBarDialog.setTabOrder(self.leftButton, self.buttonBox)

    def retranslateUi(self, E5ToolBarDialog):
        _translate = QtCore.QCoreApplication.translate
        E5ToolBarDialog.setWindowTitle(_translate("E5ToolBarDialog", "Configure Toolbars"))
        self.label.setText(_translate("E5ToolBarDialog", "&Toolbar:"))
        self.toolbarComboBox.setToolTip(_translate("E5ToolBarDialog", "Select the toolbar to configure"))
        self.newButton.setToolTip(_translate("E5ToolBarDialog", "Press to create a new toolbar"))
        self.newButton.setText(_translate("E5ToolBarDialog", "&New"))
        self.removeButton.setToolTip(_translate("E5ToolBarDialog", "Press to remove the selected toolbar"))
        self.removeButton.setText(_translate("E5ToolBarDialog", "&Remove"))
        self.renameButton.setToolTip(_translate("E5ToolBarDialog", "Press to rename the selected toolbar"))
        self.renameButton.setText(_translate("E5ToolBarDialog", "R&ename"))
        self.label_2.setText(_translate("E5ToolBarDialog", "Actions:"))
        self.label_3.setText(_translate("E5ToolBarDialog", "Current Toolbar Actions:"))
        self.actionsTree.setToolTip(_translate("E5ToolBarDialog", "Select the action to add to the current toolbar"))
        self.toolbarActionsList.setToolTip(_translate("E5ToolBarDialog", "Select the action to work on"))
        self.toolbarActionsList.setWhatsThis(_translate("E5ToolBarDialog", "<b>Current Toolbar Actions</b><p>This list shows the actions of the selected toolbar. Select an action and use the up or down button to change the order of actions or the left button to delete it. To add an action to the toolbar, select it in the list of available actions and press the right button.</p>"))
        self.upButton.setToolTip(_translate("E5ToolBarDialog", "Press to move the selected action up."))
        self.leftButton.setToolTip(_translate("E5ToolBarDialog", "Press to delete the selected action from the toolbar"))
        self.rightButton.setToolTip(_translate("E5ToolBarDialog", "Press to add the selected action to the toolbar"))
        self.downButton.setToolTip(_translate("E5ToolBarDialog", "Press to move the selected action down."))

